cart/urls.py
from django.urls import path
from.import views
app_name='addcart'

urlpatterns=[
     path('cart',views.cart,name='cart')
]

customerapp/urls.py
from django.urls import path
from.import views
app_name='customer'

 
urlpatterns =[
    
   path('main',views.main,name='main'),
     path('fruits',views.fruits,name='fruits'),
     path('master',views.master),
     path('vegetables',views.vegetables,name='vegetables'),
     path('foodgrains',views.foodgrains,name='foodgrains'),
     path('backery',views.backery,name='backery'),  
     path('',views.home,name='home'),
     path('logincustomer',views.Login,name='logincustomer'), 
     path('booking',views.booking,name='booking'), 
     path('viewcart',views.viewcart,name='viewcart'),
     path('signup',views.signup,name='signup'), 
     path('payment',views.payment,name='payment'),
     path('changepassword',views.changepassword,name='changepassword'),
     path('category',views.category,name='category') ,
      path('trackorderstatus',views.trackorderstatus,name='trackorderstatus'), 
      path('addtocartf/<int:pid>',views.addtocartf,name='addtocartf'),
      path('addtocartv/<int:pid>',views.addtocartv,name='addtocartv'),
      path('addtocartg/<int:pid>',views.addtocartg,name='addtocartg'),
     path('addtocartb/<int:pid>',views.addtocartb,name='addtocartb'),
     path('remove_from_cart/<int:cid>', views.remove_from_cart, name='remove_from_cart'),
     path('veg_delete/<int:pid>',views.deleteveg,name='veg_delete'),

      

      

      

      

   
 ]
  
  
 

grocery/urls.py
from django.urls import path
from.import views
app_name='groceryadmin'

urlpatterns = [
    
   
     path('additem',views.additem,name='additem'), 
     path('dashboard',views.dashboard,name='dashboard') ,
     path('manageorder',views.manageorder,name='manageorder'),
     path('',views.adminsignup,name='adminsignup'),
     path('adminmaster',views.adminmaster,name='adminmaster'),
     path('adminlogin',views.adminlogin,name='adminlogin'), 
     path('admindashboard',views.admindashboard,name='admindashboard'),
     path('viewproduct',views.viewproduct,name='viewproduct'), 
     path('adminhome',views.adminhome,name='adminhome'),
    

]

groceryproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('g/',include('grocery.urls')),
    path('',include('customerapp.urls')),
    path('p/',include('products.urls')),
    path('c/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from.import views



app_name='productadmin'
urlpatterns=[

     path('',views.addproduct,name='addproduct'), 
     path('viewproduct',views.viewproduct,name='viewproduct'),
     path('productmaster',views.productmaster,name='productmaster'),
     path('p_delete/<int:pid>',views.deleteproduct,name='p_delete'),
     path('p_update/<int:pid>',views.updateproduct,name='p_update'),
     path('statusupdate/<int:pid>',views.statusupdate,name='status_update')
]

grocery/models.py
from django.db import models

# Create your models here.

class Grocery(models.Model):
    name=models.TextField(db_column='name',null=True)
    number=models.PositiveIntegerField(db_column='number',null=True)
    email=models.TextField(db_column='email',null=True)
    password=models.TextField(db_column='password',null=True)


    class Meta:
        db_table='grocery_signup'

class AddItems(models.Model):
    title=models.TextField(max_length=100,null=True)
    amount=models.DecimalField(max_digits=10,decimal_places=2,null=True)
    picture=models.ImageField(upload_to='product_images/',null=True,blank=True)
    brief=models.TextField(null=True)

    class Meta:
        db_table='grocery_items'

grocery/views.py
from django.shortcuts import render,redirect
from.models import *
from django.http import JsonResponse


# from .forms import ProductForm

 

# Create your views here.


def viewproduct(request):
    return render(request,'grocery/viewproduct.html')


def dashboard(request):
    return render(request,'grocery/dashboard.html')

def manageorder(request):
    return render(request,'grocery/manageorder.html')



def adminmaster(request):
    return render(request,'grocery/adminmaster.html')

def admindashboard(request):
    return render(request,'grocery/admindashboard.html')

def adminhome(request):
    return render(request,'grocery/adminhome.html')


def adminsignup(request):
    if request.method=='POST':
        name=request.POST['name']
        number=request.POST['number']
        email=request.POST['email']
        password=request.POST['password']

        grocery=Grocery(name=name,email=email,number=number,password=password)
        grocery.save()
    return render(request,'grocery/adminsignup.html')

def adminlogin(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']

        if Grocery.objects.filter(email=email,password=password).exists():
             return redirect('groceryadmin:adminhome')
        
        else:

            return render(request,'grocery/adminlogin.html')
    return render(request,'grocery/adminlogin.html')
    
        
    



def additem(request):
        if request.method=='POST':
           title=request.POST['title']
           amount=request.POST['amount']
           picture=request.POST['picture']
           brief=request.POST['brief']  
           items=AddItems(title=title,picture=picture,amount=amount,brief=brief)
           items.save()
           return redirect('groceryadmin:admindashboard')  
        
        return render(request,'grocery/additem.html')     
        

          

grocery/templates/grocery/admindashboard.html
{% extends 'grocery/adminmaster.html' %}
{% load static %}

    {% block content %}
    <div class="container-fluid">
        <div class="row">
          <h1>Dash board</h1>
            
                <div class="col-3">
                    <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                        <div class="card-header">Total Users</div>
                        <div class="card-body">
                          <h5 class="card-title">2</h5>
                          
                          <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                        </div>
                      </div>
                     
                    </div>

                    <div class="col-3">
                        <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                            <div class="card-header">Total Products</div>
                            <div class="card-body">
                              <h5 class="card-title">2</h5>
                              
                              <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                            </div>
                          </div>
                         
                        </div>

                        <div class="col-3">
                            <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                                <div class="card-header">Total Category</div>
                                <div class="card-body">
                                  <h5 class="card-title">4</h5>
                                  
                                  <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                </div>
                              </div>
                             
                            </div>

                            <div class="col-3">
                                <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                                    <div class="card-header">New Order</div>
                                    <div class="card-body">
                                      <h5 class="card-title">2</h5>
                                      
                                      <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                    </div>
                                  </div>
                                 
                                </div>
            
        </div>
    </div>


    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                    <div class="card-header">Dispatch Order</div>
                    <div class="card-body">
                      <h5 class="card-title">1</h5>
                      
                      <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                    </div>
                  </div>
                 
                </div>
                
                <div class="col-3">
                    <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                        <div class="card-header">On The Way Order</div>
                        <div class="card-body">
                          <h5 class="card-title">0</h5>
                          
                          <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                        </div>
                      </div>
                     
                    </div>

                    <div class="col-3">
                        <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                            <div class="card-header">Delivered Order</div>
                            <div class="card-body">
                              <h5 class="card-title">0</h5>
                              
                              <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                            </div>
                          </div>
                         
                        </div>

                        <div class="col-3">
                            <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                                <div class="card-header">Cancel Order</div>
                                <div class="card-body">
                                  <h5 class="card-title">0</h5>
                                  
                                  <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                </div>
                              </div>
                             
                            </div>
                        
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                    <div class="card-header">Return Order</div>
                    <div class="card-body">
                      <h5 class="card-title">0</h5>
                      
                      <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                    </div>
                  </div>
                 
                </div>
                
                <div class="col-3">
                    <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                        <div class="card-header">Total Order</div>
                        <div class="card-body">
                          <h5 class="card-title">5</h5>
                          
                          <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                        </div>
                      </div>
                     
                    </div>

                    <div class="col-3">
                        <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                            <div class="card-header">Read Feedback</div>
                            <div class="card-body">
                              <h5 class="card-title">0</h5>
                              
                              <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                            </div>
                          </div>
                         
                        </div>

                        <div class="col-3">
                            <div class="card text-bg-info mb-3" style="max-width: 18rem;">
                                <div class="card-header">Unread Feedback</div>
                                <div class="card-body">
                                  <h5 class="card-title">1</h5>
                                  
                                  <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                </div>
                              </div>
                             
                            </div>
                        
        </div>
    </div>



    {% endblock %}

grocery/templates/grocery/adminhome.html
{% extends 'grocery/adminmaster.html' %}
{% load static %}

{% block content %}

<br><br><br>

<div class="container-fluid" style="height:700px;" >
   
    


<button  class="btn btn-primary"><a href="{% url 'groceryadmin:dashboard' %}" style="color: aliceblue;">dashboard</a></button>
<button  class="btn btn-primary"><a href="{% url 'groceryadmin:manageorder' %}" style="color: aliceblue;">Manageorder</a></button>
<button  class="btn btn-primary"><a href="{% url 'productadmin:viewproduct' %}" style="color: aliceblue;">Viewproduct</a></button>
<button  class="btn btn-primary"><a href="{% url 'productadmin:addproduct' %}" style="color: aliceblue;">Addproduct</a></button>

<button  class="btn btn-primary"><a href="{% url 'groceryadmin:admindashboard' %}" style="color: aliceblue;">AdminDashboard</a></button>

</div>






{% endblock %}

grocery/templates/grocery/adminlogin.html
{% extends 'grocery/adminmaster.html' %}
{% load static %}

    {% block content %}
    <br><br><br>
    
    <div class="container" style=" height: 700px;">
        <div class="row" >
            <div class="col-2"></div>
            <div class="col-8 login" style="border: 1px solid blue; text-align: center;" >
                <h1>LOGIN NOW</h1>
    <br><br>
    <form action="" method="post" onsubmit="">
        {% csrf_token %}
    
    <label for="">Email</label><br>
    <input style="width: 300px;" type="email" name="email" id="">
    <br>
    <br>
    <label for="">password</label><br>
    <input style="width: 300px;" type="password" name="password" id="">
    <br><br>
    <button class="logsub" type="submit" >Login</button>
    <br><br>
    <h6>don't have an account?<a  class="register" href="{% url 'groceryadmin:adminsignup' %}">register now</a></h6>
</form>
            </div>
        </div>
    </div>
   
   </div>
   {% endblock %} 
    

grocery/templates/grocery/adminmaster.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   
    <link rel="stylesheet" href="{% static 'css/adminmaster.css' %}">

    <link rel="stylesheet" href="{% static 'css/additem.css' %}">
    <link rel="stylesheet" href="{% static 'css/adminsignup.css' %}">
    <link rel="stylesheet" href="{% static 'css/adminlogin.css' %}">



<style>
  .container-fluid{
    --bs-gutter-x: -1.5rem;
}

</style>

  </head>
  <body style="background-image: linear-gradient(#2E86C1 ,#40E0D0 );background-repeat: no-repeat;">
    <div class="container-fluid" >
     
        <div class="row"    style="background-color:#3498DB ;">
         
          <div class="col-9" >
            
              <h2 > <i> <b >freshgro-Mart</b></i></h2>
          </div>
          <div class="col-3">
              <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success  style" type="submit" style="background-color: rgb(63, 109, 209);  color: #BFC9CA;">Search</button>
                </form>
              
          </div>
        
      </div>
    
     
  <div class="row"  >
      
         
    <div class="col-12" >      
      <nav class="navbar navbar-expand-lg bg-body-tertiary" style="--bs-navbar-padding-y: -0.5rem;"  >
          <div class="container-fluid" style="background-color: #85C1E9; --bs-gutter-x: -0.5rem;">
            <a class="navbar-brand" href="{% url 'customer:main' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'customer:main' %}">Category</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'productadmin:viewproduct' %}">ViewProduct</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'groceryadmin:adminhome' %}">Admin home</a>
                </li>
               
                
              </ul>
              <div class="btn-group" role="group" aria-label="Basic example">
               
                <button type="button" class="btn btn-primary"><a href="{% url 'productadmin:viewproduct' %}"><i class="fa-solid fa-cart-shopping"></i></a>add</button>
                
                <button type="button" class="btn btn-primary"><a href="{% url 'groceryadmin:adminlogin' %}"><i class="fa-solid fa-user"></i></a>user</button>
                <button type="button" class="btn btn-primary"><a href=" {% url 'groceryadmin:adminhome' %}"><i class="fa-solid fa-dumpster"></i></a>Become a seller</button>
              </div>
            </div>
          </div>
        </nav>
      </div>   
  </div>
  
      </div>
      {% block content %}

      {% endblock %}


       


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>   
</body>
</html>

grocery/templates/grocery/adminsignup.html
{% extends 'grocery/adminmaster.html' %}
{% load static %}
{% block content %}

   
    
   

    <div  >
      
        <h1 class="heading">REGISTER NOW</h1>
    
    <form action="" method="post" onsubmit="" >
        {% csrf_token %}
        
        <div class="container" style="height: 700px;">
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8"  style="border: 1px solid rgb(27, 17, 175); " >
                
           
            <table class="tablecontent">
               <tr>
                    <td class="td"> <label for="">User Name:</label></td>
                    <td class="td"><input type="text" name="name" id="" placeholder="Enter user name"></td>
                    <td class="td"> <label for="">number:</label></td>
                    <td class="td"> <input type="number" name="number" id="" placeholder="Enter contact number"></td>
                   
                </tr>
                <br>
                <tr>
                    <td class="td"> <label for="">Email:</label></td>
                    <td class="td"> <input type="email" name="email" id="" placeholder="Enter Email"></td>
                    <td class="td"><label for="">Password:</label></td>
                    <td class="td"><input type="password" name="password" id="" ></td>
                   
                   
                </tr>
                <tr>
                    <td class="td"><label for="">confirm Password:</label></td>
                    <td class="td"><input type="password" name="confirmpassword" id="" ></td>

                </tr>
                
            </table> 
            <br>
            <br>

            <button class="submit" type="submit">submit</button>
            <br><br>
            <h4 class="last">already have an account?  <a  class="log" href="{% url 'groceryadmin:adminlogin' %}">login now</a></h4>
            
       
          </div>

    </form>


    
</div>
</div>
</div>
{% endblock %}

    
   

grocery/templates/grocery/dashboard.html
{% extends 'grocery/adminmaster.html' %}
{% load static %}

    {% block content %}
    <br><br><br>
    
    </header>
    <div class="container" style="height: 700px;">
        <div class="row">
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                     <h5 class="card-title">Total users</h5>
                     </div>
                   <ul class="list-group list-group-flush">
                     <li class="list-group-item">3</li>
                     </ul>
                   <div class="card-body">
                     <a href="#" class="card-link">view details</a>
                     </div>
                 </div>
                </div>

                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                         <h5 class="card-title">total products</h5>
                         </div>
                       <ul class="list-group list-group-flush">
                         <li class="list-group-item">25</li>
                         </ul>
                       <div class="card-body">
                         <a href="#" class="card-link">view deatails</a>
                         </div>
                     </div>
                    </div>

                    <div class="col-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                             <h5 class="card-title">total categorys</h5>
                             </div>
                           <ul class="list-group list-group-flush">
                             <li class="list-group-item">10</li>
                             </ul>
                           <div class="card-body">
                             <a href="#" class="card-link">view details</a>
                             </div>
                         </div>
                        </div>

                        
        </div>
        <br><br>

        <div class="row">
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                     <h5 class="card-title">total order</h5>
                     </div>
                   <ul class="list-group list-group-flush">
                     <li class="list-group-item">55</li>
                     </ul>
                   <div class="card-body">
                     <a href="#" class="card-link">view details</a>
                     </div>
                 </div>
                

              
        </div>
        <div class="col-4">
          <div class="card" style="width: 18rem;">
              <div class="card-body">
               <h5 class="card-title">new order</h5>
               </div>
             <ul class="list-group list-group-flush">
               <li class="list-group-item">15</li>
               </ul>
             <div class="card-body">
               <a href="#" class="card-link">view details</a>
               </div>
           </div>
          </div>
        </div>
    </div>
    {% endblock %}
    
    


 

grocery/templates/grocery/manageorder.html
{% extends 'grocery/adminmaster.html' %}
{% load static %}

<body style="background-color: rgb(185, 13, 185);">
   
  
           {% block content %}



            <div class="container-fluid" style="height: 700px;">
                <div class="row">
                    <div class="col-3">
                        <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                            <div class="card-header">Total Users</div>
                            <div class="card-body">
                              <h5 class="card-title">121</h5>
                              
                              <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                            </div>
                          </div>
                         
                        </div>

                        <div class="col-3">
                            <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                                <div class="card-header">Total Products</div>
                                <div class="card-body">
                                  <h5 class="card-title">112</h5>
                                  
                                  <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                </div>
                              </div>
                             
                            </div>
                            <div class="col-3">
                                <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                                    <div class="card-header">Total Category</div>
                                    <div class="card-body">
                                      <h5 class="card-title">233</h5>
                                     
                                      <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                    </div>
                                  </div>
                                  
                                </div>

                                <div class="col-3">
                                    <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                                        <div class="card-header">New order</div>
                                        <div class="card-body">
                                          <h5 class="card-title">111</h5>
                                          
                                          <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                                        </div>
                                      </div>
                                     
                                    </div>

                                    
                    </div>
                
                <br><br>


    
        <div class="row">
            <div class="col-4">
                <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                    <div class="card-header">Total Order</div>
                    <div class="card-body">
                      <h5 class="card-title">243</h5>
                      
                      <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                    </div>
                  </div>
                  
            </div>

            <div class="col-4">
              <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                  <div class="card-header">Total Feedback</div>
                  <div class="card-body">
                    <h5 class="card-title">1245</h5>
                   
                    <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                  </div>
                </div>
               
              </div>



            <div class="col-4">
                <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
                    <div class="card-header">Total Reviews</div>
                    <div class="card-body">
                      <h5 class="card-title">1134</h5>
                      
                      <div class="card-footer bg-transparent border-success"><a href="">View Details >></a></div>
                    </div>
                  </div>
                 
            </div>

          
                  
            </div>
        </div>
      </div>
    
    {% endblock %}
          




    