cart/urls.py
from django.urls import path
from.import views
app_name='addcart'

urlpatterns=[
     path('cart',views.cart,name='cart')
]

customerapp/urls.py
from django.urls import path
from.import views
app_name='customer'

 
urlpatterns =[
    
   path('main',views.main,name='main'),
     path('fruits',views.fruits,name='fruits'),
     path('master',views.master),
     path('vegetables',views.vegetables,name='vegetables'),
     path('foodgrains',views.foodgrains,name='foodgrains'),
     path('backery',views.backery,name='backery'),  
     path('',views.home,name='home'),
     path('logincustomer',views.Login,name='logincustomer'), 
     path('booking',views.booking,name='booking'), 
     path('viewcart',views.viewcart,name='viewcart'),
     path('signup',views.signup,name='signup'), 
     path('payment',views.payment,name='payment'),
     path('changepassword',views.changepassword,name='changepassword'),
     path('category',views.category,name='category') ,
      path('trackorderstatus',views.trackorderstatus,name='trackorderstatus'), 
      path('addtocartf/<int:pid>',views.addtocartf,name='addtocartf'),
      path('addtocartv/<int:pid>',views.addtocartv,name='addtocartv'),
      path('addtocartg/<int:pid>',views.addtocartg,name='addtocartg'),
     path('addtocartb/<int:pid>',views.addtocartb,name='addtocartb'),
     path('remove_from_cart/<int:cid>', views.remove_from_cart, name='remove_from_cart'),
     path('veg_delete/<int:pid>',views.deleteveg,name='veg_delete'),

      

      

      

      

   
 ]
  
  
 

grocery/urls.py
from django.urls import path
from.import views
app_name='groceryadmin'

urlpatterns = [
    
   
     path('additem',views.additem,name='additem'), 
     path('dashboard',views.dashboard,name='dashboard') ,
     path('manageorder',views.manageorder,name='manageorder'),
     path('',views.adminsignup,name='adminsignup'),
     path('adminmaster',views.adminmaster,name='adminmaster'),
     path('adminlogin',views.adminlogin,name='adminlogin'), 
     path('admindashboard',views.admindashboard,name='admindashboard'),
     path('viewproduct',views.viewproduct,name='viewproduct'), 
     path('adminhome',views.adminhome,name='adminhome'),
    

]

groceryproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('g/',include('grocery.urls')),
    path('',include('customerapp.urls')),
    path('p/',include('products.urls')),
    path('c/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

customerapp/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name=models.TextField(db_column='name',null=True)
    number=models.PositiveIntegerField(db_column='number',null=True)
    email=models.TextField(db_column='email',null=True)
    password=models.TextField(db_column='password',null=True)


    class Meta:
        db_table='customer_signin'

customerapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from.models import *
from products.models import *
from cart.models import *




# Create your views here.
def indexhome(request):
    return render(request,'customerapp/main.html')

def fruits(request):
    fruit=Category.objects.get(c_name='Fruits')
    pdt=Addproducts.objects.filter(category=fruit)
    return render(request,'customerapp/fruits.html',{'products':pdt})

def main(request):
    return render(request,'customerapp/main.html')

def master(request):
    return render(request,'customerapp/master.html')

def category(request):
    return render(request,'customerapp/category.html')


def vegetables(request):
    vege=Category.objects.get(c_name='vegetables')
    pdts=Addproducts.objects.filter(category=vege)
    return render(request,'customerapp/vegetables.html',{'vegetable':pdts})

def foodgrains(request):
    grain=Category.objects.get(c_name='foodgrains')
    fdgns=Addproducts.objects.filter(category=grain)
    return render(request,'customerapp/foodgrains.html',{'foodgrains':fdgns})

def backery(request):
    backery=Category.objects.get(c_name='Backery')
    bkds=Addproducts.objects.filter(category=backery)
    return render(request,'customerapp/backery.html', {'backery':bkds})

def home(request):
    return render(request,'customerapp/home.html')



def booking(request):
    return render(request,'customerapp/booking.html')

def viewcart(request):
    cart_item=Cart.objects.all()
    # totalprice=sum(item.product.price*item.quantity for item in cart_item)
    return render(request,'customerapp/viewcart.html',{'cart_items':cart_item})

def payment(request):
    return render(request,'customerapp/payment.html')

def changepassword(request):
    return render(request,'customerapp/changepassword.html')


def trackorderstatus(request):
    return render(request,'customerapp/trackorderstatus.html')


def signup(request):
    if request.method=='POST':
        name=request.POST['name']
        number=request.POST['number']
        email=request.POST['email']
        password=request.POST['password']

        customer=Customer(name=name,email=email,number=number,password=password)
        customer.save()
    return render (request,'customerapp/signup.html')

def Login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']

        try:
            customer=Customer.objects.get(email=email,password=password)
        except Customer.DoesNotExist:
            err='invalid user name or password'
            return render(request,'customerapp/login.html',{'error':err})
        return redirect('customer:main')
        
    return render(request,'customerapp/login.html')

def Dashboard(request):
    return render(request,'customerapp/main.html')



def addtocartf(request,pid):
    if request.method=='POST':
       product=Addproducts.objects.get(id=pid)
       cart_item,created=Cart.objects.get_or_create(product=product)
       if not created:
           cart_item.quantity+=1
           cart_item.save()
    return redirect('customer:fruits')
def addtocartv(request,pid):
    if request.method=='POST':
       product=Addproducts.objects.get(id=pid)
       cart_item,created=Cart.objects.get_or_create(product=product)
       if not created:
           cart_item.quantity+=1
           cart_item.save()
    return redirect('customer:vegetables')
    
def addtocartg(request,pid):
    if request.method=='POST':
       product=Addproducts.objects.get(id=pid)
       cart_item,created=Cart.objects.get_or_create(product=product)
       if not created:
           cart_item.quantity+=1
           cart_item.save()
    return redirect('customer:foodgrains')
def addtocartb(request,pid):
    if request.method=='POST':
       product=Addproducts.objects.get(id=pid)
       cart_item,created=Cart.objects.get_or_create(product=product)
       if not created:
           cart_item.quantity+=1
           cart_item.save()
    return redirect('customer:backery')
   

def remove_from_cart(request,cid):
    if request.method == 'POST':
        cart_item=Cart.objects.get(id=cid)
        cart_item.delete()
    return redirect('customer:viewcart')




def deleteveg(request,pid):
    Addvegetables.objects.get(id=pid).delete()
    
    return redirect('customer:viewcart')

customerapp/templates/customerapp/backery.html
{% extends 'customerapp/master.html' %}
{% load static %}

{% block content %}

    <h1><b style="margin-left: 400px;color: blue;">Backery,Diarys & Bevereges</b></h1>
    <br></br>
    <div class="container-fluid" style="background-color: rgb(165, 214, 198);padding: 20px;">
        <div class="row">
          {% for p in backery %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                  {% if p.img and p.img.url %}
                    <img src="  {{p.img.url}} " class="card-img-top" alt="..." width="250px" height="250px" >
                    {% else %}
                    <p>no image</p>
                    {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{p.name}}</h5>
                      <p class="card-text"> {{p.price}}</p>
                      <form action="{% url 'customer:addtocartb' p.id %}" method="post">
                        {% csrf_token %}
                        <label for="">quantity</label>
                        <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                        <button class="btn btn-primary" type="submit">add to cart</button>
                      </form>
                      
                     
                    </div>
                  </div>
            </div>

            {% endfor %}

           {% endblock %}

customerapp/templates/customerapp/foodgrains.html
{% extends 'customerapp/master.html' %}
{% load static %}

     {% block content %}

    <h1><b style="margin-left: 400px;color: blue;">Foodgrains,masalas&oils</b></h1>
    <div class="container-fluid" style="background-color: rgb(165, 214, 198);padding: 20px;">
        <div class="row">
          {% for p in foodgrains %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                  {% if p.img and p.img.url %}
                    <img src=" {{p.img.url}} " class="card-img-top" alt="..." width="250px" height="250px" >
                    {% else %}
                    <p>no image</p>
                    {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{p.name}}</h5>
                      <p class="card-text">{{p.price}}</p>
                      <form action="{% url 'customer:addtocartg' p.id %}" method="post">
                        {% csrf_token %}
                        <label for="">quantity</label>
                        <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                        <button class="btn btn-primary" type="submit">add to cart</button>
                      </form>
                      
                     
                    </div>
                  </div>
            </div>
        {% endfor %}

      {% endblock %}

customerapp/templates/customerapp/fruits.html
{% extends 'customerapp/master.html' %}
{% load static %}

  {% block content %}
    


        <h1><b style="color: blue; margin-left: 600px;">Fruits</b></h1> 
        <br><br>
    <div class="container-fluid" style="background-color: rgb(165, 214, 198);padding: 20px;">
        <div class="row">
          {% for p in products %}
          
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                  {% if p.img and p.img.url %}
                    <img src=" {{p.img.url}} " class="card-img-top" alt="..." width="250px" height="250px" >
                    {% else %}
                    <p>no image</p>
                    {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{p.name}}</h5>
                      <p class="card-text">{{p.price}}</p>
                      <form action="{% url 'customer:addtocartf' p.id %}" method="post">
                        {% csrf_token %}
                        <label for="">quantity</label>
                        <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                        <button class="btn btn-primary" type="submit">add to cart</button>
                      </form>
                      
                     
                    </div>
                  </div>
            </div>
            {% endfor %}
            

   {% endblock %}
    
    
    
  

customerapp/templates/customerapp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
 <style>
    a{
text-decoration: none;

    }
    button{
        background-color: rgb(26, 209, 26);
        border-color:  rgb(26, 209, 26);
        width: 200px;

    }


span,h3,h1,h5{
    color: blue;
    font-style: italic;
    margin-left: 150px;
}
    
h1{
    color: limegreen;
}

 </style>

</head>
<body>

          <div class="container-fluid" style="background-image: linear-gradient(#F7DC6F,#FDEBD0 );border: 10px solid rgb(181, 240, 87);">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <h1 >freshgro-Mart</h1>
                    <span>Fresh And Oraganic</span>
                        <h3  > Your Daily Need Products</h3> 
                    <img src=" {% static 'images/homeimage31.jpg' %}"  alt="..."  width="600px">
                

                    <br><br>
                        
                        <button><a href="{% url 'customer:signup' %}">get started</a></button>
                        <button><a href="{% url 'customer:logincustomer' %}">Login</a></button> <br><br><br>
                        <h5><a href="">www.freshgromart.in</a></h5>
                    
    
                   
                </div>
                </div>

               
            </div>
          </div>      
           
              
            
       
        
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> 
</body>
</html>

customerapp/templates/customerapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
       .login{
        margin-top: 150px;

       }
       button{
    background-color: rgb(16, 199, 16);
    width: 100px;
    height: 40px;
    border-color:rgb(16, 199, 16) ;
    color: aliceblue;
    font-size: large;
       }
       a{
    text-decoration: none;
    color: black;
}
h6{
    display: block;
}
.register{
    color: rgb(48, 71, 202);
}
    </style>
</head>
<body style="background-image: url(https://media.istockphoto.com/id/1445897927/photo/pink-padlock-cartoon-style-copy-space-text-3d-rendering-illustration.jpg?s=612x612&w=0&k=20&c=Nj-m42s6cwEzVQUgV6exexcahuJObU_WNMLhyM5Tq9c=);background-repeat: no-repeat; background-size: cover;">

    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-8 login">
                <h1>LOGIN NOW</h1>
    <br><br>
    <form action="" method="post" onsubmit="return loginform()">
        {% csrf_token %}
    
    <label for="">email</label><br>
    <input style="width: 300px;" type="email" name="email" id="name">
    <br>
    <br>
    <label for="">password</label><br>
    <input style="width: 300px;" type="password" name="password" id="pswd">
    <br><br>
    <input type="submit" value="login">
    <br><br>
    <h6>don't have an account?<a  class="register" href="{% url 'customer:signup' %}">register now</a></h6>
</form>
</div>
        </div>
    </div>
   
   

    
</div> 

<script>
    function loginform(){
    username=document.getElementById("name").value ;
    password=document.getElementById("pswd").value ;
    if(username=="" && password==""){
        alert("please enter username and password");
        return false
    }
    else{
        return true
    }

}
</script>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>  
</body>
</html>
   

customerapp/templates/customerapp/master.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
   
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="stylesheet" href="{% static 'css/addproduct.css' %}">
     <link rel="stylesheet" href="{% static 'css/grocerymain.css' %}">
    
    <!-- <link rel="stylesheet" href="{% static 'css/fruits.css' %}">  -->
    <link rel="stylesheet" href="{% static 'css/viewcart.css' %}"> 
    
    <link rel="stylesheet" href="{% static 'css/payment.css' %}">
    <link rel="stylesheet" href="{% static 'css/changepassword.css' %}">
    <link rel="stylesheet" href="{% static 'css/trackorderstatus.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/viewcart.css' %}">
    

      
</head>
<body>
  
    <div class="container-fluid" >
     
      <div class="row"    style="background-color:#5DADE2;">
       
       
        <div class="col-9" >
          
            <h2 > <i> <b >freshgro-Mart</b></i></h2>
        </div>
        <div class="col-3">
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success  style" type="submit" style="background-color: rgb(63, 109, 209);  color: #BFC9CA;">Search</button>
              </form>
            
        </div>
      
    </div>
  
   
<div class="row"  >
    
       
 <div class="col-12">
       
    <nav class="navbar navbar-expand-lg bg-body-tertiary"  style="--bs-navbar-padding-y: -0.5rem;"  >
        <div class="container-fluid" style="background-color: #AED6F1;">
          <a class="navbar-brand" href="{% url 'customer:main' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:category' %}">Category</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'customer:main' %}"></a>
              </li>
              
             </ul>

            <div class="btn-group" role="group" aria-label="Basic example">
             
              <button type="button" class="btn btn-primary" > <a href="{% url 'customer:viewcart' %}"><i class="fa-solid fa-cart-shopping"></i>cart</a></button>
              
              <button type="button" class="btn btn-primary"><a href="{% url 'customer:logincustomer' %}"><i class="fa-solid fa-user"></i></a>user</button>
              <button type="button" class="btn btn-primary"><a href=" {% url 'groceryadmin:adminhome' %}"> <i class="fa-solid fa-dumpster"></i></a>Become a seller</button>
              <button type="button" class="btn btn-primary"><a href=" {% url 'customer:home' %}"> Logout</a></button>

            </div>
          </div>
        </div>
        </div>
      </nav>
    </div>   
</div>

    </div>
     
   {% block content %}







   {% endblock %}
   <br><br><br>

   <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item ">
        <a class="page-link" href="{% url 'customer:home' %}">previous</a>
      </li>
      <li class="page-item"><a class="page-link" href="{% url 'customer:main' %}">1</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'customer:category' %}">2</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'customer:fruits' %}">3</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'customer:vegetables' %}">4</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'customer:foodgrains' %}">5</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'customer:backery' %}">6</a></li>

      <li class="page-item">
        <a class="page-link" href="{% url 'customer:viewcart' %}">Next</a>
      </li>
    </ul>
  </nav>
    
<br><br>

   <div class="container-fluid">
  <div class="row">

    <div class="col-3">
      <div class="card text-bg-light mb-3" style="width: 18rem;">
        <div class="card-body " style="background-color: #b8cad6;">
          <h5 class="card-title">freshgro-Mart</h5>
          <p class="card-text">fresh and organic your daily need products</p>
         <a href=""><i class="fa-brands fa-facebook"></i></a> 
          <a href=""><i class="fa-brands fa-twitter"></i></a>
          <a href=""><i class="fa-brands fa-instagram"></i></a>
          <a href=""><i class="fa-brands fa-linkedin"></i></a>
          
        </div>
      </div>
    </div>

    <div class="col-3">
      
      
       <a href="#" class="list-group-item list-group-item-action "> <b> Contact Info</b></a>
        <a href="#" class="list-group-item list-group-item-action"><i class="fa-solid fa-phone-flip"></i>+233-6758905</a>
        <a href="#" class="list-group-item list-group-item-action"><i class="fa-solid fa-phone-flip"></i>+233-348765545</a>
        <a href="#" class="list-group-item list-group-item-action"><i class="fa-sharp fa-solid fa-envelope"></i>freshgromart@gmail.com</a>
        <a href="#" class="list-group-item list-group-item-action"><i class="fa-solid fa-location-dot"></i>mumbai,india-400104</a>
       
     
    </div>

    <div class="col-3">
      
        
       <a href="#" class="list-group-item list-group-item-action"><b>Quick Links</b></a>
       <a href="#" class="list-group-item list-group-item-action">Home</a>
       <a href="#" class="list-group-item list-group-item-action">Payment</a>
       <a href="#" class="list-group-item list-group-item-action"></a>
       <a href="#" class="list-group-item list-group-item-action">signup</a>
      
    
      
    </div>

    <div class="col-3">
     
        
        <a href="#" class="list-group-item list-group-item-action"><b>Newsletter</b></a>
        <a href="#" class="list-group-item list-group-item-action">subscribe for latest updates</a>
        <a href="#" class="list-group-item list-group-item-action"><input type="email" name="" id="" placeholder="your email"></a>
        <a href="#" class="list-group-item list-group-item-action"><button>subscribe</button></a>
        <a href="#" class="list-group-item list-group-item-action"></a>
       
     

     
      
    </div>




  </div>
</div>

 
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/login.js' %}"></script>
    <script src="{% static 'js/signup.js' %}"></script>
</body>
</html>

customerapp/templates/customerapp/signup.html
{% extends 'customerapp/master.html' %}
{% load static %}

   
    
      {% block content %}

      <div style="background-image: url(https://media.istockphoto.com/id/1403824688/photo/shopping-trolley-grocery-push-cart-minimalist-concept.jpg?s=612x612&w=0&k=20&c=u2yfU1MS8OYLx2TFHIT0gAqrzommSKtc9-dcljXO-0w=);background-repeat: no-repeat;background-size: cover;">
      
            <h1 class="heading">REGISTER NOW</h1>
        
<form action="" method="post" onsubmit="return signupform()" >
            {% csrf_token %}
            
            <div class="content" >
               
                <table class="tablecontent">
                    <tr>
                        <td class="td" > <label for="">First Name:</label></td>
                        <td class="td"><input type="text" name="" id="" placeholder="Enter First Name"></td>
                        <td class="td"> <label for="">Last Name:</label></td>
                        <td class="td"><input type="text" name="" id="" placeholder="Enter Last Name"></td>
                        </tr>
                        
            
                        <tr>
                        <td class="td"> <label for="">User Name:</label></td>
                        <td class="td"><input type="text" name="name" id="name" placeholder="Enter user name"></td>
                        <td class="td"> <label for="">number:</label></td>
                        <td class="td"> <input type="number" name="number" id="number" placeholder="Enter contact number"></td>
                       
                    </tr>
                    <tr>
                        <td class="td"> <label for="">Email:</label></td>
                        <td class="td"> <input type="email" name="email" id="email" placeholder="Enter Email"></td>
                        <td class="td"><label for="">Password:</label></td>
                        <td class="td"><input type="password" name="password" id="pswd1" ></td>
                       
                    </tr>
                    <tr>
                        <td class="td"><label for="">confirm password:</label></td>
                        <td class="td"><input type="password" name="password" id="pswd2" placeholder="confirm password"></td>
                        <!-- <td class="td"> <label for="">city:</label></td>
                        <td class="td"> <input type="city" name="" id="" placeholder="enter city"></td> -->
                    </tr>
                        <!-- <tr>
                        <td class="td"><label for="">Full Address</label></td>
                        <td class="td">  <textarea name="" id="" cols="30" rows="2" placeholder="enter your address"></textarea></td>
                        <td class="td"><label for="">Pincode:</label></td>
                        <td><input type="text" name="" id=""></td>
                    </tr> -->
                </table>
                <br>
                <br>

                <button class="submit" type="submit" >submit</button>
                <br><br>
                <h4 class="last">already have an account?  <a  class="log" href="{% url 'customer:logincustomer' %}">login now</a></h4>
                
               
              </div>

            
    </form>


    <script>
        function signupform(){
// username=document.getElementById("name").value;
// email=document.getElementById("email").value ;
// number=document.getElementById("number").value ;
// password=document.getElementById("pswd1").value ;
// confirmpassword=document.getElementById("pswd2").value ;
alert('hello')

// if (fullname==""||number==""||email==""||pswd1==""||pswd2=="")
// {
//  document.getElementById('error').innerHTML="all field must be filled out"
//  return false

// }
// else if( pswd1!=pswd2)
// {
//   alert("password not matched")
// }
// else{
//   alert("password matched")  

//   }
  
}
</script>
        {% endblock %}

  
  

customerapp/templates/customerapp/viewcart.html
{% extends 'customerapp/master.html' %}
{% load static %}


{% block content %}
<style>
  .styled-table {
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    width: 100%;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
.styled-table thead tr {
    background-color: #3e7ed3;
    color: #ffffff;
    text-align: left;
}
.styled-table th,
.styled-table td {
    padding: 12px 15px;
}

.styled-table tbody tr {
    border-bottom: 1px solid #dddddd;
}

.styled-table tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

.styled-table tbody tr:last-of-type {
    border-bottom: 2px solid #3196be;
}
.styled-table tbody tr.active-row {
    font-weight: bold;
    color: #5f9de4;
}
</style>
<h1>View Cart</h1>
<br>
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
        <button type="button"  class="bu" class="btn btn-primary btn-lg"><a href="{% url 'customer:main' %}">Continue shopping</a></button>
        <button type="button" class="bu"  class="btn btn-secondary btn-lg"><a href="{% url 'customer:payment' %}">Buy Now</a></button>
        <button type="button" class="bu"  class="btn btn-secondary btn-lg"><a href="{% url 'customer:trackorderstatus' %}">Track orders</a></button>

<br><br></div> 
<div class="col-3"></div>
</div>

{% for i in cart_items %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{i.product.img.url}}" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{i.product.name}}</h5>
                  <p class="card-text">{{i.product.price}}</p>
                  <p class="card-text">{{i.quantity}}</p>
                  <p class="card-text">
                    <form method="post" action="{% url 'customer:remove_from_cart' i.id %}">
                      {% csrf_token %}
                      <input type="hidden" name="cart_item_id" value="{{ item.id }}">
                      <button type="submit" class="btn btn-danger">Remove</button>
                    </form>
                  </p>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>
{% endfor %}

        </div>
    

 

  

{% endblock %}