cart/urls.py
from django.urls import path
from.import views
app_name='addcart'

urlpatterns=[
     path('cart',views.cart,name='cart')
]

customerapp/urls.py
from django.urls import path
from.import views
app_name='customer'

 
urlpatterns =[
    
   path('main',views.main,name='main'),
     path('fruits',views.fruits,name='fruits'),
     path('master',views.master),
     path('vegetables',views.vegetables,name='vegetables'),
     path('foodgrains',views.foodgrains,name='foodgrains'),
     path('backery',views.backery,name='backery'),  
     path('',views.home,name='home'),
     path('logincustomer',views.Login,name='logincustomer'), 
     path('booking',views.booking,name='booking'), 
     path('viewcart',views.viewcart,name='viewcart'),
     path('signup',views.signup,name='signup'), 
     path('payment',views.payment,name='payment'),
     path('changepassword',views.changepassword,name='changepassword'),
     path('category',views.category,name='category') ,
      path('trackorderstatus',views.trackorderstatus,name='trackorderstatus'), 
      path('addtocartf/<int:pid>',views.addtocartf,name='addtocartf'),
      path('addtocartv/<int:pid>',views.addtocartv,name='addtocartv'),
      path('addtocartg/<int:pid>',views.addtocartg,name='addtocartg'),
     path('addtocartb/<int:pid>',views.addtocartb,name='addtocartb'),
     path('remove_from_cart/<int:cid>', views.remove_from_cart, name='remove_from_cart'),
     path('veg_delete/<int:pid>',views.deleteveg,name='veg_delete'),

      

      

      

      

   
 ]
  
  
 

grocery/urls.py
from django.urls import path
from.import views
app_name='groceryadmin'

urlpatterns = [
    
   
     path('additem',views.additem,name='additem'), 
     path('dashboard',views.dashboard,name='dashboard') ,
     path('manageorder',views.manageorder,name='manageorder'),
     path('',views.adminsignup,name='adminsignup'),
     path('adminmaster',views.adminmaster,name='adminmaster'),
     path('adminlogin',views.adminlogin,name='adminlogin'), 
     path('admindashboard',views.admindashboard,name='admindashboard'),
     path('viewproduct',views.viewproduct,name='viewproduct'), 
     path('adminhome',views.adminhome,name='adminhome'),
    

]

groceryproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('g/',include('grocery.urls')),
    path('',include('customerapp.urls')),
    path('p/',include('products.urls')),
    path('c/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from.import views



app_name='productadmin'
urlpatterns=[

     path('',views.addproduct,name='addproduct'), 
     path('viewproduct',views.viewproduct,name='viewproduct'),
     path('productmaster',views.productmaster,name='productmaster'),
     path('p_delete/<int:pid>',views.deleteproduct,name='p_delete'),
     path('p_update/<int:pid>',views.updateproduct,name='p_update'),
     path('statusupdate/<int:pid>',views.statusupdate,name='status_update')
]

products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    c_name=models.TextField(max_length=50,null=True)
    c_image=models.ImageField(upload_to='images',blank=True,null=True)
    def __str__(self):
        return self.c_name


class Addproducts(models.Model):
    name=models.TextField(max_length=100,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2,null=True)
    img=models.ImageField(upload_to='images',null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    status=models.TextField(null=True)
    def __str__(self):
        return self.name

    class Meta:
        db_table='product_items'

class Addvegetables(models.Model):
    name=models.TextField(max_length=100,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2,null=True)
    img=models.ImageField(upload_to='images',null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    status=models.TextField(null=True)

    class Meta:
        db_table='vegetable_items'

class Addbackery(models.Model):
    name=models.TextField(max_length=100,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2,null=True)
    img=models.ImageField(upload_to='images',null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    status=models.TextField(null=True)

    class Meta:
        db_table='backery_items'

class Addfoodgrain(models.Model):
    name=models.TextField(max_length=100,null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2,null=True)
    img=models.ImageField(upload_to='images',null=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    status=models.TextField(null=True)

    class Meta:
        db_table='foodgrain_items'
    

products/views.py
from django.shortcuts import render,redirect
from.models import *
from django.http import JsonResponse


# Create your views here.

def productmaster(request):
    return render(request,'products/productmaster.html')




def addproduct(request):
        if request.method=='POST':
           name=request.POST['name']
           price=request.POST['price']
           
           image = request.FILES.get('images')
           
           
           status=request.POST['status'] 

           items=Addproducts(name=name,price=price,img=image,status=status)
           items.save()
           
           return redirect('productadmin:viewproduct')  
           
        return render(request,'products/addproduct.html')   


def viewproduct(request):
    pdts=Addproducts.objects.all()
    veg=Addvegetables.objects.all()
    baks=Addbackery.objects.all()
    fdgs=Addfoodgrain.objects.all()
    return render (request,'products/viewproduct.html',{'product':pdts,
                                                        'vegetable':veg,
                                                        'backery':baks,
                                                        'foodgrain':fdgs
                                                        })

def deleteproduct(request,pid):
     Addproducts.objects.get(id=pid).delete()
    
     return redirect('productadmin:viewproduct')


def updateproduct(request,pid):
     pdt=Addproducts.objects.get(id=pid)
    
     if request.method=='POST':
          name=request.POST['name']
          price=request.POST['price']
          image=request.FILES.get('images')
          
          pdt.name=name
          pdt.price=price
          pdt.image=image
         

          pdt.save()
          return redirect('productadmin:viewproduct')
     return render(request,'products/updateproduct.html',{'product':pdt,
                                                       
                                                          })

def statusupdate(request,pid):
     p_status=Addproducts.objects.get(id=pid)
     p_veg=Addvegetables.objects.get(id=pid)
     p_backery=Addbackery.objects.get(id=pid)
     p_foodgrain=Addfoodgrain.objects.get(id=pid)

     if p_status.status=='0':
          Addproducts.objects.filter(id=pid).update(status='1')

     else:
          Addproducts.objects.filter(id=pid).update(status='0')


     if p_veg.status=='0':
          Addvegetables.objects.filter(id=pid).update(status='1')

     else:
          Addvegetables.objects.filter(id=pid).update(status='0')


     if p_backery.status=='0':
          Addbackery.objects.filter(id=pid).update(status='1')
     else:
          Addbackery.objects.filter(id=pid).update(status='0')
          

     if p_foodgrain.status=='0':
          Addfoodgrain.objects.filter(id=pid).update(status='1')
     else:
          Addfoodgrain.objects.filter(id=pid).update(status='0')

     return redirect('productadmin:viewproduct')

        
def addvegetable(request):
      if request.method=='POST':
           name=request.POST['name']
           price=request.POST['price']
           
           image = request.FILES.get('images')
           
           status=request.POST['status'] 

           items=Addvegetables(name=name,price=price,img=image,status=status)
           items.save()
           
           return redirect('productadmin:viewproduct')  
           
      return render(request,'products/addproduct.html')   


def addbackery(request):
      if request.method=='POST':
           name=request.POST['name']
           price=request.POST['price']
           
           image = request.FILES.get('images')
           status=request.POST['status'] 

           items=Addbackery(name=name,price=price,img=image,status=status)
           items.save()
           
           return redirect('productadmin:viewproduct')  
           
      return render(request,'products/addproduct.html')  
 
def addfoodgrain(request):
     if request.method=='POST':
          name=request.POST['name']
          price=request.POST['price']
          image=request.FILES.get('images')
          status=request.POST['status']
          items=Addfoodgrain(name=name,price=price,img=image,status=status)
          items.save()
           
          return redirect('productadmin:viewproduct')  
           
     return render(request,'products/addproduct.html')  

          

products/templates/products/addproduct.html
{% extends 'products/productmaster.html' %}
{% load static %}
{% block content %}
    <div class="container" style="height: 700px;">
        <div class="row">
          <div class="col-2"></div>
          <div class="col-10">
          <div>
            <h1>ADD NEW PRODUCT</h1>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-8">
    
                  <form action="{% url 'productadmin:addproduct' %}" method="post" novalidate encrypt="multipart/form-data">
                    
                    {% csrf_token %}
    
    
                    <div class="border">
                        <div class="container overflow-hidden text-center">
                            <div class="row gy-5">
                            
                              <div class="col-6">
                                <div class="p-3"><input type="text" name="name" id="" placeholder="enter product name"></div>
                              </div>
                              <div class="col-6">
                                <div class="p-3"><input type="text" name="price" id="" placeholder="enter product price"> </div>
                              </div>
                              <div class="col-6">
                                <div class="p-3"> <label for="">select category:</label><select name="" id=""  >
                                  <option value="">fruits</option>
                                  <option value="">vegetables</option>
                                  <option value="">food grains</option>
                                  <option value="">backery</option>
                                </select></div>
                              </div>
                              <div class="col-6">
                                <div class="p-3"><input type="file" name="images" accept="image/*" id="" placeholder="no file choosen"></div>
                              </div>
                              <div>
                                
                                
                              <div>
                                
                                <input  type="text" name="status" id="" placeholder="status">
                              </div>
                              <div>
                               <input type="submit" value="Add Product">
                              </div>
                            </div>
                            </div>
                          
                    </div>
                    
                
    
                </div>
            </div>
        </div>
      </div>
    
        </div>
    
      </div>
    
    </form>
        
 
{% endblock %}

products/templates/products/productmaster.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
<style>
  .container-fluid{
    --bs-gutter-x: -1.5rem;
}

</style>

  </head>
  <body style="background-image: -webkit-repeating-linear-gradient(#2E86C1 ,#40E0D0 ); background-size: cover;background-repeat: no-repeat;">
    <div class="container-fluid " >
     
        <div class="row"    style="background-color: #5DADE2 ;">
         
          <div class="col-9" >
            
              <h2 > <i> <b >freshgro-Mart</b></i></h2>
          </div>
          <div class="col-3">
              <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success  style" type="submit" style="background-color: rgb(63, 109, 209);  color: #BFC9CA;">Search</button>
                </form>
              
          </div>
        
      </div>
    
     
  <div class="row"  >
      
         
    <div class="col-12" >      
      <nav class="navbar navbar-expand-lg bg-body-tertiary" style="--bs-navbar-padding-y: -0.5rem;"  >
          <div class="container-fluid" style="background-color: #85C1E9 ; --bs-gutter-x: -0.5rem;">
            <a class="navbar-brand" href="{% url 'customer:main' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'groceryadmin:adminhome' %}">Admin home</a>
                </li>
               
                
              </ul>
              <div class="btn-group" role="group" aria-label="Basic example">
               
                <button type="button" class="btn btn-primary" > <a href=""><i class="fa-solid fa-cart-shopping"></i></a>add</button>
                
                <button type="button" class="btn btn-primary"><a href=""><i class="fa-solid fa-user"></i></a>user</button>
                <button type="button" class="btn btn-primary"><a href=" "> <i class="fa-solid fa-dumpster"></i></a>Become a seller</button>
              </div>
            </div>
          </div>
        </nav>
      </div>   
  </div>
  
      </div>
      {% block content %}

      {% endblock %}


       


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>   
</body>
</html>

products/templates/products/updateproduct.html
{% extends 'products/productmaster.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
      <div class="col-2"></div>
      <div class="col-10">
      <div>
        <h1>UPDATE PRODUCT</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-6">

              <form action="" method="post" encrypt="multipart/form-data">
                
                {% csrf_token %}


                <div class="border">
                    <div class="container overflow-hidden text-center">
                        <div class="row gy-5">
                          <div class="col-6">
                            <div class="p-3"><input type="text" name="name" id="" placeholder="enter product name"></div>
                          </div>
                          <div class="col-6">
                            <div class="p-3"><input type="text" name="price" id="" placeholder="enter product price"> </div>
                          </div>
                          <div class="col-6">
                            <!-- <div class="p-3"> <label for="">select category:</label><select name="" id=""  >
                              <option value="">fruits</option>
                              <option value="">vegetables</option>
                              <option value="">food grains</option>
                              <option value="">backery</option>
                            </select></div>
                          </div> -->
                          <div class="col-6">
                            <div class="p-3"><input type="file" name="image" id="" placeholder="no file choosen"></div>
                          </div>
                          <div>
                            
                            <input  type="text" name="description" id="" placeholder="enter product details">
                          </div>
                          <div>
                           <input type="submit" value="Add Product">
                          </div>
                        </div>
                      </div>
                </div>
                
            

            </div>
        </div>
    </div>
  </div>

    </div>

  </div>
</form>
{% endblock %}

products/templates/products/viewproduct.html
{% extends 'products/productmaster.html' %}
{% load static %}

{% block content %}
<h1>view products</h1>

<div class="container-fluid">
    <div class="row" >
        {% for p in product %}

        <div class="col-4"style="margin-top: 40px;">
            <div class="card" style="width: 18rem;">
                {% if p.img and p.img.url %}
                
                <img src="{{p.img.url}}" class="card-img-top" alt="..." width="250px" height="250px" >
                

                {% else %}
                <p>no image</p>
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title">{{p.name}}</h5>
                  <p class="card-text">{{p.price}} </p>

                  <a href="{% url 'productadmin:status_update' p.id %}" >{{p.status}}</a>
                  <a href="{% url 'productadmin:p_update' p.id %}" class="btn btn-primary">update</a>
                  <a href="{% url 'productadmin:p_delete' p.id %}" class="btn btn-primary">delete</a>
                 
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}


   